### ISSUE TITLE
Use `use`

### ISSUE THREAD

**Issue by calebeby** [jstransformers/jstransformer-stylus#15]
Hi, I need to use [jeet](http://jeet.gs/) on my project, but it is not documented how to use stylus's `use` (with `jstransformer-stylus`).

**Comment by andy-hanson** [comment]
Do you have the `jstransformer-stylus` package installed? This is the repository for that tool, not for [stylus](http://stylus-lang.com) itself.

**Comment by calebeby** [comment]
Yes, I do. I am wondering how to use Stylus's `use` functionality with JSTransformers

**Comment by calebeby** [comment]
@ForbesLindesay @RobLoach @andy-hanson Is this implemented? How do I use this?

**Comment by calebeby** [comment]
I figured out how to use one module:

```coffee
use: jeet()
```
after
```coffee
jeet = require('jeet')
```
but how do I use more than one? I tried passing an array to `use`, but then it errors with:

```js
TypeError: fn.call is not a function
  at Renderer.use
```

I'm thinking that c7079a8 has something to do with it?

**Comment by calebeby** [comment]
@RobLoach I figured it out. Can you change

```js
  // special options with single parameter through their function names
  for (var k in specialSingle) {
    renderer[k](specialSingle[k]);
  }
```

to

```js
  // special options with single parameter through their function names
  for (var k in specialSingle) {
    var options = []
    if (typeof(specialSingle[k]) === 'object') {
      options = specialSingle[k];
    } else {
      options = [specialSingle[k]];
    }
    for (var i in options) {
      var option = options[i]
      renderer[k](option);
    }
  }
```
[here](https://github.com/jstransformers/jstransformer-stylus/blob/master/index.js#L46)

Thanks.

**Comment by RobLoach** [comment]
Looks like a great improvement. Mind sending in a Pull Request? Then you'll get git author credit as a contributor :wink:

**Comment by calebeby** [comment]
Yeah, sure. I'll try to make a pull request this afternoon

**Comment by calebeby** [comment]
Or now. #16

**Comment by RobLoach** [comment]
Great work!
