### ISSUE TITLE
Extension Support through `use`

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-stylus#18]
Spawned off from https://github.com/RobLoach/metalsmith-jstransformer/issues/3 , it would be great to be able to extend Stylus with:

- http://npm.im/axis
- http://npm.im/jeet
- http://npm.im/rupture

Possibly add the extensions through Engine Options from https://github.com/jstransformers/jstransformer/issues/172 .

**Comment by calebeby** [comment]
I believe this is already supported:

```coffee
stylus = require('jstransformer')(require('jstransformer-stylus'))

file =
  """
  @require('jeet')

  .foo
    col(1/2)
  """
stylus.renderAsync file,
  use: [ 'jeet', 'rupture', 'axis' ]
```

I fixed this in #16 / #15 
Can you publish to NPM so people don't have to install through git?

**Comment by RobLoach** [comment]
I added a [`use` test](https://github.com/jstransformers/jstransformer-stylus/tree/master/test/use). Would be good to extend this to be able to pass in a string of the module name or something, in case JavaScript is not available. Like pass in a JSON object.

**Comment by calebeby** [comment]
Sure, I'll see if I can do that.

**Comment by RobLoach** [comment]
`1.2.0` is out as well! :+1:

**Comment by calebeby** [comment]
:balloon: :tada:

**Comment by calebeby** [comment]
Do you approve of #19?

`1.2.1`?
