### ISSUE TITLE
How to enable nib?

### ISSUE THREAD

**Issue by frontEndWebDev** [jstransformers/jstransformer-stylus#28]
Hello, is there any option to enable [nib](https://github.com/tj/nib) ? It would be nice.

**Comment by calebeby** [comment]
Hi Bohdan,

You can use stylus by passing it into `use`

```js
var stylus = require('jstransformer')(require('jstransformer-stylus'))

stylus.render(code, {
  use: [
    require('nib')
  ]
})
```

**Comment by frontEndWebDev** [comment]
Thanks for quick response, but how I can use it in context of pug file? For example:
```
p
  :stylus(require('nib'))
    stylus code
```

**Comment by calebeby** [comment]
I believe you might be able to use

```pug
p
  :stylus(use=['nib'])
    stylus code
```

**Comment by frontEndWebDev** [comment]
Unfortunatery this dont wokr, thi eather

**Comment by calebeby** [comment]
It worked for me

https://runkit.com/calebeby/nib-in-stylus-in-pug

**Comment by frontEndWebDev** [comment]
Thanks for the tip, but the final working solution is:
```
//template.pug
p
  :stylus(use=['nib'])
    @import nib
    .some-class
      clearfix() // stylus mixin for test
```

**Comment by frontEndWebDev** [comment]
Can I make a commit in README.md with this example?
