### ISSUE TITLE
Cannot find module 'promise'

### ISSUE THREAD

**Issue by Volune** [jstransformers/jstransformer-stylus#3]
Hi,

I have a `Cannot find module 'promise'` error when using `jstransformer-stylus@0.0.6`
`promise` should probably be in the dependencies, not in the devDependencies.

Here is my package.json, if that helps:
```
{
    "dependencies": {
        "minimist": "~1.1.1",
        "jade": "~1.10.0",
        "jstransformer-stylus": "~0.0.6"
    },
    "engines": {
        "node": ">=0.10"
    }
}
```

(I finally added promise in my package.json as a workaround)

**Comment by tunnckoCore** [comment]
sorry for the mess.. just that automation and fast fingers some time... ;d

released and published as `0.0.7`

**Comment by Volune** [comment]
Great, just tested it, thanks for the quick fix.

**Comment by RobLoach** [comment]
@tunnckoCore Thanks for fixing it up!
